-- NOOKAMBIKA STORE
-- Data retention rules
--
-- Customer:
--   Orders / purchases: visible for 3 months
-- Admin:
--   Orders, order items and settlements: retained for 1 year
-- Wishlist:
--   private to each customer and retained for 1 year
--
-- IMPORTANT:
-- This script assumes the existing tables:
-- orders, order_items, settlements
-- and a wishlist table named wishlists.
--
-- If wishlists does not exist yet, create it with the schema below.

CREATE TABLE IF NOT EXISTS wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(customer_id, product_id)
);

CREATE INDEX IF NOT EXISTS idx_orders_created_at
ON orders(created_at);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id
ON order_items(order_id);

CREATE INDEX IF NOT EXISTS idx_settlements_created_at
ON settlements(created_at);

CREATE INDEX IF NOT EXISTS idx_wishlists_created_at
ON wishlists(created_at);

CREATE INDEX IF NOT EXISTS idx_wishlists_customer_id
ON wishlists(customer_id);


-- ============================================================
-- 1. CUSTOMER ORDER HISTORY
-- ============================================================
-- The database keeps order records for 1 year.
-- The customer website must only query the latest 3 months.

-- Example customer query:
-- SELECT *
-- FROM orders
-- WHERE customer_id = :customer_id
--   AND created_at >= NOW() - INTERVAL '3 months'
-- ORDER BY created_at DESC;


-- ============================================================
-- 2. ADMIN RECORD RETENTION
-- ============================================================
-- Orders older than 1 year are deleted.
-- order_items are deleted first because they reference orders.

CREATE OR REPLACE FUNCTION cleanup_nookambika_old_records()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN

    -- Delete order items belonging to orders older than 1 year.
    DELETE FROM order_items
    WHERE order_id IN (
        SELECT id
        FROM orders
        WHERE created_at < NOW() - INTERVAL '1 year'
    );

    -- Delete old settlements.
    DELETE FROM settlements
    WHERE created_at < NOW() - INTERVAL '1 year';

    -- Delete orders older than 1 year.
    DELETE FROM orders
    WHERE created_at < NOW() - INTERVAL '1 year';

    -- Delete wishlist records older than 1 year.
    DELETE FROM wishlists
    WHERE created_at < NOW() - INTERVAL '1 year';

END;
$$;


-- ============================================================
-- 3. RUN CLEANUP
-- ============================================================
-- Run this function once per day using a Supabase scheduled
-- function / pg_cron job.
--
-- SELECT cleanup_nookambika_old_records();


-- ============================================================
-- 4. WISHLIST PRIVACY
-- ============================================================
-- A customer's wishlist must only be returned for that customer.
-- Do NOT expose all wishlist rows to normal customers.
--
-- The application/backend should always use:
--
-- WHERE customer_id = authenticated_customer_id
--
-- Admin should not display another customer's wishlist as a
-- public/shared wishlist.


-- ============================================================
-- 5. RETENTION SUMMARY
-- ============================================================
--
-- Customer:
--   Orders/purchases visible: 3 months
--
-- Admin:
--   Orders: 1 year
--   Order items: 1 year
--   Settlements: 1 year
--
-- Wishlist:
--   Owner only
--   Database retention: 1 year
--
-- After 1 year:
--   Expired orders/order items/settlements/wishlist records
--   are removed from the database.
--
-- Customer accounts are NOT deleted by this cleanup.
